plugins/redmine_finance/config/routes.rb
# This file is a part of Redmine Finance (redmine_finance) plugin,
# simple accounting plugin for Redmine
#
# Copyright (C) 2011-2016 Kirill Bezrukov
# http://www.redminecrm.com/
#
# redmine_finance is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_finance is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_finance.  If not, see <http://www.gnu.org/licenses/>.

# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :accounts
resources :operations do
  collection do
      post :bulk_update
      get :bulk_edit, :context_menu, :auto_complete
      delete :bulk_destroy
  end
end
resources :operation_categories
resources :operation_comments, :only => [:create, :destroy]
resources :operation_invoices, :only => [:create, :destroy]
resources :operation_relations, :only => [:create, :destroy]

resources :operation_imports, :only => [:new, :create]

resources :projects do
  resources :operations

  resources :operation_imports, :only => [:new, :create, :show] do
    member do
      get :settings
      post :settings
      get :mapping
      post :mapping
      get :run
      post :run
    end
  end
end

resources :projects do
  resources :accounts
end

plugins/redmine_finance/app/models/account.rb
# This file is a part of Redmine Finance (redmine_finance) plugin,
# simple accounting plugin for Redmine
#
# Copyright (C) 2011-2016 Kirill Bezrukov
# http://www.redminecrm.com/
#
# redmine_finance is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_finance is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_finance.  If not, see <http://www.gnu.org/licenses/>.

class Account < ActiveRecord::Base
  unloadable

  before_destroy :check_integrity

  belongs_to :project
  has_many :operations, :dependent => :destroy
  belongs_to :assigned_to, :class_name => 'Principal', :foreign_key => 'assigned_to_id'

  scope :visible, lambda { |*args| joins(:project).where(Project.allowed_to_condition(args.first || User.current, :view_finances)) }
  scope :named, lambda {|arg| where("LOWER(#{table_name}.name) = LOWER(?)", arg.to_s.strip)}
  scope :by_project, lambda {|project_id| where(:project_id => project_id) unless project_id.blank? }

  acts_as_customizable
  acts_as_watchable
  acts_as_attachable :view_permission => :view_finances
  acts_as_priceable :amount, :debit, :credit

  before_save :calculate_amount

  validates_presence_of :project, :currency
  validates_uniqueness_of :name

  def calculate_amount
    @account_amount_was = self[:amount]
    self.amount = self.operations.current.approved(true).income.sum(:amount) - self.operations.approved(true).expense.current.sum(:amount)
  end

  def amount
    @amount ||= debit - credit
  end

  def total_amount
    @total_amount ||= self.operations.approved(true).income.sum(:amount) - self.operations.approved(true).expense.sum(:amount)
  end


  def debit
    @debit ||= self.operations.current.approved(true).income.sum(:amount)
  end

  def credit
    @credit ||= self.operations.current.approved(true).expense.sum(:amount)
  end

  def visible?(usr=nil)
    (usr || User.current).allowed_to?(:view_finances, self.project)
  end

  def editable_by?(usr=nil)
    (usr || User.current).allowed_to?(:edit_accounts, self.project)
  end

  def destroyable_by?(usr=nil)
    (usr || User.current).allowed_to?(:delete_accounts, self.project)
  end

  # def balance(balance_date)
  #   self.operations.income.order("#{Operation.table_name}.operation_date DESC").select{|o| o.operation_date <= balance_date}.sum(&:amount) - self.operations.expense.order("#{Operation.table_name}.operation_date DESC").select{|o| o.operation_date < balance_date}.sum(&:amount)
  # end

  def to_s
    "#{name} (#{currency})"
  end

  def recipients
    notified = []
    # Author and assignee are always notified unless they have been
    # locked or don't want to be notified
    # notified << author if author
    if assigned_to
      notified += (assigned_to.is_a?(Group) ? assigned_to.users : [assigned_to])
    end
    notified = notified.select {|u| u.active?}

    notified += project.notified_users
    notified.uniq!
    # Remove users that can not view the contact
    notified.reject! {|user| !visible?(user)}
    notified.collect(&:mail)
  end

  def created_on
    created_at
  end

  def account_amount_was
    @account_amount_was
    # if amount_changed? && amount_was.present?
    #   @account_amount_was ||= amount_was
    # end
  end

  private

  def check_integrity
    raise Exception.new("Can't delete account") if Operation.where(:account_id => self.id).any?
  end

  def helpers
    ActionController::Base.helpers
  end

end

plugins/redmine_finance/app/controllers/accounts_controller.rb
# This file is a part of Redmine Finance (redmine_finance) plugin,
# simple accounting plugin for Redmine
#
# Copyright (C) 2011-2016 Kirill Bezrukov
# http://www.redminecrm.com/
#
# redmine_finance is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_finance is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_finance.  If not, see <http://www.gnu.org/licenses/>.

class AccountsController < ApplicationController
  unloadable

  menu_item :operations

  before_filter :find_account, :only => [:show, :edit, :update, :destroy]
  before_filter :find_account_project, :only => [:new, :create]
  before_filter :find_optional_project, :only => :index
  before_filter :authorize, :except => :index

  accept_api_auth :index, :show, :create, :update, :destroy

  helper :contacts
  helper :watchers
  helper :custom_fields
  helper :timelog
  helper :attachments
  helper :issues
  helper :operations
  include ContactsHelper
  include AttachmentsHelper

  def index
    scope = Account.visible
    scope = scope.where(:project_id => @project) if @project
    @accounts = scope.order("#{Account.table_name}.name")
    @accounts_count = scope.count
  end

  def show
    @operations = find_operations
  end

  def new
    @account = Account.new
  end

  def create
    @account = Account.new(params[:account])
    @account.project = @project
    if @account.save
      attachments = Attachment.attach_files(@account, (params[:attachments] || (params[:operation] && params[:operation][:uploads])))
      render_attachment_warning_if_needed(@account)
      flash[:notice] = l(:notice_successful_create)

      respond_to do |format|
        format.html { redirect_to :action => "show", :id => @account }
        format.api  { render :action => 'show', :status => :created, :location => account_url(@account) }
      end
    else
      respond_to do |format|
        format.html { render :action => 'new' }
        format.api  { render_validation_errors(@account) }
      end
    end
  end

  def update
    (render_403; return false) unless @account.editable_by?(User.current)
    if @account.update_attributes(params[:account])
      attachments = Attachment.attach_files(@account, (params[:attachments] || (params[:operation] && params[:operation][:uploads])))
      render_attachment_warning_if_needed(@account)
      flash[:notice] = l(:notice_successful_update)
      respond_to do |format|
        format.html { redirect_to :action => "show", :id => @account }
        format.api  { head :ok }
      end
    else
      respond_to do |format|
        format.html { render :action => "edit"}
        format.api  { render_validation_errors(@account) }
      end
    end
  end

  def destroy
    (render_403; return false) unless @account.destroyable_by?(User.current)
    unless @account.operations.empty?
      flash[:error] = l(:label_finance_can_not_delete_account)
    else
      @account.destroy
      flash[:notice] = l(:notice_successful_delete)
    end
    respond_to do |format|
      format.html { redirect_to :action => "index", :project_id => @account.project }
      format.api  { head :ok }
    end
  end

  private

  def find_account
    @account = Account.eager_load(:project).find(params[:id])
    raise Unauthorized unless @account.visible?
    @project ||= @account.project
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def find_account_project
    project_id = params[:project_id] || (params[:account] && params[:account][:project_id])
    @project = Project.find(project_id)
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def find_operations(pages=true)
    scope = @account.operations
    scope = scope.eager_load(:account => :project).where(:accounts => {:project_id => @project})
    scope = scope.includes(:contact, :category)

    scope = scope.where(:category_id => params[:category_id]) unless params[:category_id].blank?
    scope = scope.where(:contact_id => params[:contact_id]) unless params[:contact_id].blank?
    scope = scope.where(["#{Operation.table_name}.operation_date BETWEEN ? AND ?", @from, @to]) if @from && @to

    scope = scope.order("#{Operation.table_name}.operation_date DESC")
    scope = scope.visible

    @operations_count = scope.count

    if pages
      @limit =  per_page_option
      @operations_pages = Paginator.new(@operations_count, @limit, params[:page])
      @offset = @operations_pages.offset

      scope = scope.limit(@limit).offset(@offset)
      @operations = scope
    end

    scope.all
  end

end

plugins/redmine_finance/app/helpers/accounts_helper.rb
# encoding: utf-8
#
# This file is a part of Redmine Finance (redmine_finance) plugin,
# simple accounting plugin for Redmine
#
# Copyright (C) 2011-2016 Kirill Bezrukov
# http://www.redminecrm.com/
#
# redmine_finance is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_finance is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_finance.  If not, see <http://www.gnu.org/licenses/>.

module AccountsHelper
end

plugins/redmine_finance/app/views/accounts/_form.html.erb
<%= error_messages_for 'account' %>

<div class="box tabular">

  <p class="name"><%= f.text_field :name, :size => 80, :required => true %></p>
  <p><%= f.select :currency, collection_for_currencies_select(ContactsSetting.default_currency, ContactsSetting.major_currencies), :label => l(:label_account_currency), :include_blank => false, :required => true  %>
  </p>

  <p><%= f.select :assigned_to_id, (@project.assignable_users.collect {|m| [m.name, m.id]}), :include_blank => true, :label => l(:field_assigned_to) %></p>
  <% custom_field_values = @account.custom_field_values %>
  <div class="splitcontent">
    <div class="splitcontentleft">
    <% i = 0 %>
    <% split_on = (custom_field_values.size / 2.0).ceil - 1 %>
    <% custom_field_values.each do |value| %>
      <p><%= custom_field_tag_with_label :account, value, :required => value.custom_field.is_required? %></p>
    <% if i == split_on -%>
    </div><div class="splitcontentright">
    <% end -%>
    <% i += 1 -%>
    <% end -%>
    </div>
  </div>

<p><%= f.text_area :description, :cols => 60, :rows => 5, :class => 'wiki-edit' %><%# wikitoolbar_for 'account_description' %></p>


</div>
<fieldset><legend><%= l(:label_attachment_plural) %></legend>
<p><%= render :partial => 'attachments/form', :locals => {:container => @account} %></p>
</fieldset>
<br>

plugins/redmine_finance/app/views/accounts/_list.html.erb
<h3><%= l(:label_account_plural) %></h3>

<% if @project.accounts.any? %>
<table class="list accounts">
  <thead><tr>
  <th><%= l(:field_name) %></th>
  <th><%= l(:label_account_balance) %></th>
  <th></th>
  </tr></thead>
  <tbody>
<% for account in @project.accounts %>
  <% unless account.new_record? %>
  <tr class="<%= cycle 'odd', 'even' %>">
  <td><%= link_to_if_authorized h(account.name), { :controller => 'accounts', :action => 'edit', :id => account } %></td>
  <td class="money"><%= account.amount_to_s %></td>
  <td class="buttons">
    <%= link_to_if_authorized l(:button_delete), {:controller => 'accounts', :action => 'destroy', :id => account}, :method => :delete, :confirm => l(:text_are_you_sure), :class => 'icon icon-del' %>
  </td>
  </tr>
  <% end %>
<% end %>
    </tbody>
</table>
<% else %>
<p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

<p><%= link_to_if_authorized l(:label_account_new), :controller => 'accounts', :action => 'new', :project_id => @project, :class => 'icon icon-add' %></p>

plugins/redmine_finance/app/views/accounts/_operations.html.erb
<%= form_tag({}) do -%>
  <%= hidden_field_tag 'back_url', url_for(params) %>
  <%= hidden_field_tag 'project_id', @project.id if @project %>
  <div class="autoscroll">
      <table class="list">
        <thead>
        <tr>
          <th class="checkbox hide-when-print"><%= link_to image_tag('toggle_check.png'), {}, :onclick => 'toggleListSelection(this); return false;',
                                                             :title => "#{l(:button_check_all)}/#{l(:button_uncheck_all)}" %>
          </th>

          <th>#</th>
          <th><%= l(:label_operation_date) %></th>
          <th><%= l(:label_operation_income) %></th>
          <th><%= l(:label_operation_expense) %></th>
          <th><%= l(:label_account_balance) %></th>
          <th><%= l(:label_operation_category) %></th>
          <th><%= l(:field_description) %></th>
          <th><%= l(:label_contact) %></th>
        </tr>
        </thead>
        <% previous_balance = @account.total_amount %>
        <% @operations.each do |operation| %>
        <tr style="text-align: center;white-space: nowrap;" class="hascontextmenu operation <%= cycle('odd', 'even') %>  <%= 'income' if operation.is_income? %> <%= 'not-approved' if RedmineFinance.operations_approval? && !operation.is_approved? %> <%= 'planned-operation' if operation.operation_date > Time.now  %>">
          <td class="checkbox hide-when-print"><%= check_box_tag("ids[]", operation.id, false, :id => nil) %></td>
          <td class="id"><%= link_to operation.id, operation_path(operation) %></td>
          <td class="operation_date"><%= link_to format_date(operation.operation_date), operation_path(operation) %></td>
          <td class="money income" style="text-align:right;"><%= operation.amount_to_s if operation.is_income? %></td>
          <td class="money expense" style="text-align:right;"><%= operation.amount_to_s unless operation.is_income? %></td>
          <td class="money balance"><%= price_to_currency(previous_balance, operation.currency) %></td>
          <td class="category"><%= operation.category  %></td>
          <td class="description" style="text-align:left;"><small><%= link_to truncate(operation.description, :length => 100), operation_path(operation, :project_id => @project) if operation.description %></small></td>
          <td class="contact" style="text-align:left;"><%= contact_tag(operation.contact) unless operation.contact.blank? %></td>
        </tr>
        <% previous_balance = account_current_balance(previous_balance, operation) %>
        <% end %>
        <tr class="total">
          <th colspan="3" class="money"><%= l(:label_finance_total) %>:</th><th class="money sum"><%=  @account.debit_to_s %></th><th class="money sum"><%=  @account.credit_to_s %></th><th colspan="4"></th>
        </tr>
      </table>
  </div>
<% end %>
<%= context_menu url_for( {:controller => "operations", :action => "context_menu"} )%>
<%= javascript_tag "$('.operation_list tr.operation.planned-operation:last').addClass('last');" %>

plugins/redmine_finance/app/views/accounts/_stat.html.erb
<div id="accounts_stat">
  <div class="contextual">
    <%= link_to l(:label_new), new_project_account_path(@project) if User.current.allowed_to?(:edit_accounts, @project) %>
  </div>

  <h3><%= l(:label_account_plural) %></h3>


  <table class="accounts-stat">
    <% @accounts.each do |account| %>
    <tr>
      <th><%= link_to account.name, account_path(account) %></th>
      <td class="sum"><%= price_to_currency(@approved_amount_by_account[account.id],  account.currency) if @approved_amount_by_account[account.id] %></td>
    </tr>
    <% end %>
  </table>
</div>

<% if RedmineFinance.operations_approval? && (!@disapproved_income.blank? || !@disapproved_expense.blank?) %>
<div id="disapproved_operations">
  <h3><%= l(:label_finance_disapproved) %></h3>


  <table class="accounts-stat">
      <% unless @disapproved_income.blank? %>
      <tr class="disapproved income">
        <th><%= link_to l(:label_finance_disapproved_income), disapproved_operations_url(true) %></th>
        <td class="sum"><%= prices_collection_by_currency(@disapproved_income).join('<br/>').html_safe -%></td>
      </tr>
      <% end %>
      <% unless @disapproved_expense.blank? %>
      <tr class="disapproved expense">
        <th><%= link_to l(:label_finance_disapproved_expense), disapproved_operations_url(false) %></th>
        <td class="sum"><%= prices_collection_by_currency(@disapproved_expense).join('<br/>').html_safe -%></td>
      </tr>
      <% end %>

  </table>
</div>
<% end %>

plugins/redmine_finance/app/views/accounts/edit.html.erb
<h2><%= l(:label_account_edit) %></h2>

<%= labelled_form_for :account, @account, :url => {:action => 'update', :id => @account.id}, :html => { :multipart => true, :method => :put, :id => 'account_form'} do |f|  %> 
  <%= render :partial => 'form', :locals => {:f => f}  %> 
  <%= submit_tag l(:button_save) -%>
<% end -%>

<% content_for :header_tags do %>
  <%= javascript_include_tag :finance, :plugin => 'redmine_finance'  %>
  <%= stylesheet_link_tag :finance, :plugin => 'redmine_finance' %>
<% end %>

plugins/redmine_finance/app/views/accounts/index.html.erb
<h2><%= l(:label_account_plural) %></h2>

<table class="list accounts">
  <thead><tr>
  <th><%= l(:field_name) %></th>
  <th><%= l(:label_account_debit) %></th>
  <th><%= l(:label_account_credit) %></th>
  <th><%= l(:label_account_balance) %></th>
  </tr></thead>
  <tbody>
<% @accounts.each do |account| %>
  <tr class="<%= cycle 'odd', 'even' %>">
    <td><%= link_to h(account.name), account_path(account) %></td>
    <td class="money debit"><%= account.debit_to_s %></td>
    <td class="money credit"><%= account.credit_to_s %></td>
    <td class="money balance"><%= account.amount_to_s %></td>
  </tr>
<% end %>
    </tbody>
</table>

<p><%= link_to_if_authorized l(:label_account_new), :controller => 'accounts', :action => 'new', :project_id => @project, :class => 'icon icon-add' %></p>

plugins/redmine_finance/app/views/accounts/new.html.erb
<h2><%= l(:label_account_new) %></h2>

<%= labelled_form_for :account, @account, :url => {:action => 'create', :project_id => @project}, :html => { :multipart => true, :id => 'account_form'} do |f|  %> 
  <%= render :partial => 'form', :locals => {:f => f}  %> 
  <%= submit_tag l(:button_save) -%>
<% end -%>


<% content_for :header_tags do %>
  <%= stylesheet_link_tag :finance, :plugin => 'redmine_finance' %>
<% end %>

plugins/redmine_finance/app/views/accounts/show.html.erb
<div class="contextual">
  <%= watcher_link(@account, User.current) %>
  <%= link_to_if_authorized l(:button_edit), {:controller => "accounts", :action => "edit", :id => @account}, :class => 'icon icon-edit' unless @account.nil? %>
  <%= link_to_if_authorized l(:button_delete), {:controller => "accounts", :action => "destroy", :id => @account}, :confirm => l(:text_are_you_sure), :method => :delete, :class => 'icon icon-del' unless @account.nil? %>
</div>
<h2><%= "#{l(:label_account)} ##{@account.id}" %></h2>
<div class="account details">

<div class="subject">
<h3><%= "#{@account.name }: #{@account.amount_to_s}" %></h3>
</div>

<table class="attributes">
<%= render_custom_fields_rows(@account) %>
<%= call_hook(:view_accounts_show_details_bottom, :account => @account) %>
</table>

<% if @account.description? || (@account.attachments && @account.attachments.any?) -%>
<hr />
<% if @account.description? %>
<div class="description">
  <p><strong><%=l(:field_description)%></strong></p>
  <div class="wiki">
  <% attachments = nil %>
  <% attachments = @account.attachments %>
  <%= textilizable @account, :description, :attachments => attachments %>
  </div>
</div>
<% end %>
<%= link_to_attachments @account, :thumbnails => true %>
<% end -%>

<%= call_hook(:view_accounts_show_description_bottom, :account => @account) %>

<% unless @operations.empty? %>
<hr />
<div id="contact_list" class="operation_list">
  <div class="contextual">
  <% if User.current.allowed_to?(:edit_operations, @project) %>
    <%= link_to l(:button_add), new_operation_path(:project_id => @project, :account_id => @account) %>
  <% end %>
  </div>

  <p><strong><%=l(:label_operation_plural)%></strong></p>
  <%= render :partial => 'operations' %>
  <span class="pagination"><%= pagination_links_full @operations_pages, @operations_count %></span>
</div>
<% end %>

</div>



<% content_for :sidebar do %>

<% end %>

<% html_title "#{l(:label_account)} ##{@account.id}: #{@account.name}" %>

<% content_for :header_tags do %>
  <meta name = "format-detection" content = "telephone=no">
<% end %>